spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.123.3:3306/fund?useSSL=true&characterEncoding=UTF-8
      username: xkrato
      password: xcwwy
      # 配置初始化大小（默认0）、最小、最大（默认8）
      initial-size: 1
      min-idle: 1
      max-active: 8
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大。 默认为false
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-open-prepared-statements: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000

      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效 默认为true
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效 默认为false
      test-on-return: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true


3des:
  key: 326a23480c26bc89246f85f3e8012345e782654bd8712509

send-grid:
  email:
    sender: xuchuang0426@qq.com
    receiver: xuchuang0426@outlook.com
  subject:
    fund: 基金经理变更，确认是否需要调仓
  content:
    fund: 基金经理发生变更，基金：
  api-key: 8496C18139090062C6F1BF505BC0F6C8D8A003B0FC4F0868EE17E706876BA5E03C3151EF09A2B29AFB5D6BFBC27EA91500CAACF8886659300A92EF7F23A211B18A2A4E1342A347EB
