package com.xkrato.fund.domain.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundManagerExample {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public FundManagerExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andUuidIsNull() {
      addCriterion("uuid is null");
      return (Criteria) this;
    }

    public Criteria andUuidIsNotNull() {
      addCriterion("uuid is not null");
      return (Criteria) this;
    }

    public Criteria andUuidEqualTo(String value) {
      addCriterion("uuid =", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidNotEqualTo(String value) {
      addCriterion("uuid <>", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidGreaterThan(String value) {
      addCriterion("uuid >", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidGreaterThanOrEqualTo(String value) {
      addCriterion("uuid >=", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidLessThan(String value) {
      addCriterion("uuid <", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidLessThanOrEqualTo(String value) {
      addCriterion("uuid <=", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidLike(String value) {
      addCriterion("uuid like", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidNotLike(String value) {
      addCriterion("uuid not like", value, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidIn(List<String> values) {
      addCriterion("uuid in", values, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidNotIn(List<String> values) {
      addCriterion("uuid not in", values, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidBetween(String value1, String value2) {
      addCriterion("uuid between", value1, value2, "uuid");
      return (Criteria) this;
    }

    public Criteria andUuidNotBetween(String value1, String value2) {
      addCriterion("uuid not between", value1, value2, "uuid");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andFundNameIsNull() {
      addCriterion("fund_name is null");
      return (Criteria) this;
    }

    public Criteria andFundNameIsNotNull() {
      addCriterion("fund_name is not null");
      return (Criteria) this;
    }

    public Criteria andFundNameEqualTo(String value) {
      addCriterion("fund_name =", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameNotEqualTo(String value) {
      addCriterion("fund_name <>", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameGreaterThan(String value) {
      addCriterion("fund_name >", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameGreaterThanOrEqualTo(String value) {
      addCriterion("fund_name >=", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameLessThan(String value) {
      addCriterion("fund_name <", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameLessThanOrEqualTo(String value) {
      addCriterion("fund_name <=", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameLike(String value) {
      addCriterion("fund_name like", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameNotLike(String value) {
      addCriterion("fund_name not like", value, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameIn(List<String> values) {
      addCriterion("fund_name in", values, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameNotIn(List<String> values) {
      addCriterion("fund_name not in", values, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameBetween(String value1, String value2) {
      addCriterion("fund_name between", value1, value2, "fundName");
      return (Criteria) this;
    }

    public Criteria andFundNameNotBetween(String value1, String value2) {
      addCriterion("fund_name not between", value1, value2, "fundName");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateIsNull() {
      addCriterion("employment_date is null");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateIsNotNull() {
      addCriterion("employment_date is not null");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateEqualTo(String value) {
      addCriterion("employment_date =", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateNotEqualTo(String value) {
      addCriterion("employment_date <>", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateGreaterThan(String value) {
      addCriterion("employment_date >", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateGreaterThanOrEqualTo(String value) {
      addCriterion("employment_date >=", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateLessThan(String value) {
      addCriterion("employment_date <", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateLessThanOrEqualTo(String value) {
      addCriterion("employment_date <=", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateLike(String value) {
      addCriterion("employment_date like", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateNotLike(String value) {
      addCriterion("employment_date not like", value, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateIn(List<String> values) {
      addCriterion("employment_date in", values, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateNotIn(List<String> values) {
      addCriterion("employment_date not in", values, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateBetween(String value1, String value2) {
      addCriterion("employment_date between", value1, value2, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andEmploymentDateNotBetween(String value1, String value2) {
      addCriterion("employment_date not between", value1, value2, "employmentDate");
      return (Criteria) this;
    }

    public Criteria andSendFlagIsNull() {
      addCriterion("send_flag is null");
      return (Criteria) this;
    }

    public Criteria andSendFlagIsNotNull() {
      addCriterion("send_flag is not null");
      return (Criteria) this;
    }

    public Criteria andSendFlagEqualTo(String value) {
      addCriterion("send_flag =", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagNotEqualTo(String value) {
      addCriterion("send_flag <>", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagGreaterThan(String value) {
      addCriterion("send_flag >", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagGreaterThanOrEqualTo(String value) {
      addCriterion("send_flag >=", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagLessThan(String value) {
      addCriterion("send_flag <", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagLessThanOrEqualTo(String value) {
      addCriterion("send_flag <=", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagLike(String value) {
      addCriterion("send_flag like", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagNotLike(String value) {
      addCriterion("send_flag not like", value, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagIn(List<String> values) {
      addCriterion("send_flag in", values, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagNotIn(List<String> values) {
      addCriterion("send_flag not in", values, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagBetween(String value1, String value2) {
      addCriterion("send_flag between", value1, value2, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andSendFlagNotBetween(String value1, String value2) {
      addCriterion("send_flag not between", value1, value2, "sendFlag");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("create_time is null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("create_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeEqualTo(Date value) {
      addCriterion("create_time =", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotEqualTo(Date value) {
      addCriterion("create_time <>", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThan(Date value) {
      addCriterion("create_time >", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("create_time >=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThan(Date value) {
      addCriterion("create_time <", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
      addCriterion("create_time <=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIn(List<Date> values) {
      addCriterion("create_time in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotIn(List<Date> values) {
      addCriterion("create_time not in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeBetween(Date value1, Date value2) {
      addCriterion("create_time between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
      addCriterion("create_time not between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNull() {
      addCriterion("update_time is null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNotNull() {
      addCriterion("update_time is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeEqualTo(Date value) {
      addCriterion("update_time =", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotEqualTo(Date value) {
      addCriterion("update_time <>", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThan(Date value) {
      addCriterion("update_time >", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("update_time >=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThan(Date value) {
      addCriterion("update_time <", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
      addCriterion("update_time <=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIn(List<Date> values) {
      addCriterion("update_time in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotIn(List<Date> values) {
      addCriterion("update_time not in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeBetween(Date value1, Date value2) {
      addCriterion("update_time between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
      addCriterion("update_time not between", value1, value2, "updateTime");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * fund_manager
   *
   * @mbg.generated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * fund_manager
   *
   * @mbg.generated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}
