package com.xkrato.fund.mapper;

import com.xkrato.fund.domain.FundManager;
import com.xkrato.fund.domain.FundManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    long countByExample(FundManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    int deleteByExample(FundManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    int insert(FundManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    int insertSelective(FundManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    List<FundManager> selectByExample(FundManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FundManager record, @Param("example") FundManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FundManager record, @Param("example") FundManagerExample example);
}