package com.xkrato.fund.mapper;

import com.xkrato.fund.domain.Fund;
import com.xkrato.fund.domain.FundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    long countByExample(FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    int deleteByExample(FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    int insert(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    int insertSelective(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    List<Fund> selectByExample(FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Fund record, @Param("example") FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Fund record, @Param("example") FundExample example);
}