package com.xkrato.fund.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fund
 */
public class Fund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * Database Column Remarks:
     *   基金id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   基金名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   基金经理id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     * Database Column Remarks:
     *   基金经理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     * Database Column Remarks:
     *   发送状态：0-初始状态，1-待发送，2-发送中，3-发送超时，4-发送成功，9-发送失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.send_status
     *
     * @mbg.generated
     */
    private String sendStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.uuid
     *
     * @return the value of fund.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.uuid
     *
     * @param uuid the value for fund.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.id
     *
     * @return the value of fund.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.id
     *
     * @param id the value for fund.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.name
     *
     * @return the value of fund.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.name
     *
     * @param name the value for fund.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.manager_id
     *
     * @return the value of fund.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.manager_id
     *
     * @param managerId the value for fund.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.manager_name
     *
     * @return the value of fund.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.manager_name
     *
     * @param managerName the value for fund.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.send_status
     *
     * @return the value of fund.send_status
     *
     * @mbg.generated
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.send_status
     *
     * @param sendStatus the value for fund.send_status
     *
     * @mbg.generated
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.create_time
     *
     * @return the value of fund.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.create_time
     *
     * @param createTime the value for fund.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund.update_time
     *
     * @return the value of fund.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund.update_time
     *
     * @param updateTime the value for fund.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}